from .connection import get_connection
from .operations import *
from .queries import *

__all__ = [
    "get_connection",
    "db_execute_fetch_all",
    "db_execute_fetch_one",
    "db_execute_insert_update_delete",
    "db_execute_scalar",
    "db_get_all_employees",
    "db_get_employee_by_id",
    "db_get_employee_count",
    "db_create_employee",
    "db_update_employee",
    "db_delete_employee",   
    "db_create_user",
    "db_get_users",
    "db_get_user_by_id",
    "db_get_user_by_username",
    "db_get_user_by_email",
    "db_update_last_login",
    "db_update_user",
    "db_delete_user",
    "db_change_password",
    "db_update_last_login",   

    "GET_ALL_EMPLOYEES",
    "GET_EMPLOYEE_BY_ID",
    "CREATE_EMPLOYEE",
    "UPDATE_EMPLOYEE",
    "DELETE_EMPLOYEE",
    "GET_EMPLOYEE_COUNT",
    "SQL_GET_USERS",
    "SQL_GET_USER_BY_ID",
    "SQL_CREATE_USER",
    "SQL_UPDATE_USER",
    "SQL_DELETE_USER",
    "SQL_CHANGE_PASSWORD",
    "SQL_GET_USER_BY_USERNAME",
    "SQL_GET_USER_BY_EMAIL",
    "SQL_REGISTER_USER",
    "SQL_UPDATE_LAST_LOGIN",
]